### ISSUE TITLE
Augment system so EOB pdfs are generated for each approved Reimbursement and stored in S3

### ISSUE THREAD

**Issue by timtraversy** [timtraversy/department-projects#12]
Each approved reimbursement should have an EOB file generated which will be included with the check from CheckIssuing

**Tasks**
- [ ] To `Reimbursement` add new private helper method `_download_eob_pdf_if_able`. This method takes a tempfile arg and returns type `bool`. True if a file has been loaded into tempfile, False otherwise.
- [ ] `_download_eob_pdf_if_able` should noop and return False if the `self.eob_pdf_s3_key` is None.
- [ ] In `_download_eob_pdf_if_able` if `self.eob_pdf_s3_key` is set then use `core.s3utils.S3Client.download` to download the PDF file into`tempfile` and return True. For `s3_bucket` use `AWS_S3_BUCKET_EOB_PDFS` from `settings.py` and for `s3_key` us the value of `self.eob_pdf_s3_key`.
