### ISSUE TITLE
As an employer, I would like to be able to bulk upload my employees via a CSV so I can more quickly onboard them to Bento.

### ISSUE THREAD

**Issue by timtraversy** [timtraversy/department-projects#19]
**Describe the feature**
In Release 84, we implemented the ability to enroll members in Bento directly from the employer portal. This required us to add a new constraint that Patient records are also create when when new employees are added to the system.

To provide some context on that, there were only two ways to be eligible for enrollment in the past. Your records were either created via an EDI ingest, which is a file format that when ingested can create Patients, Employees, and Coverage in our system. Or you you signed up in the Bento app (thus creating a Patient record) to enroll in a benefit provided by your employer, facilitated by Bento's app based enrollment implementation for employers. 

A Patient record is required to be able to enroll in our system, because this is what ultimately is associated with an active benefit.

We updated the UI/API for creating employees one by one, but we ran out of time to update the bulk upload implementation, which now needs to follow the same behavior.

There will be a few steps to this, which will be outlined in the specification checklists below.

**Tasks**
- [ ] Determine new CSV format
- [ ] Update `EmployeeViewSet.bulk_create`

**Acceptance Tests**
- [ ] As an employer on the employees table...
- [ ] If I click Upload...
- [ ] A dialog opens with a file input asking for an employee roster CSV

**Additional context**
