### ISSUE TITLE
New/Changed Email: System email to inform members that their enrollment is open and no action is needed unless they want to update their plan

### ISSUE THREAD

**Issue by timtraversy** [timtraversy/department-projects#20]
**Describe the feature**
Brief Description (what, when, why): System email to inform members that their plan is renewing This applies to current members who's plan is renewing without any changes to the plan (group, group access, and in-office plan)

New, Replacement, or Update: New

Parameters Included: custom.member_first_name, custom.plan_name, DCS link

Recipient Type: member

Test Email:
   Link: https://app.hubspot.com/email/6242788/details/30133965489/performance
   Test Email ID:30133965489

Live Email:
   Link: https://app.hubspot.com/email/6242788/details/35969135473/performance
   Live Email ID: 35969135473

**All system emails that have additions/deletions/changes to the payload MUST be a new template and will involve development work**

System Email process document: https://docs.google.com/document/d/1sOx2CVk4_S3X0Dd6psxgNMFtrea4VwfOPC7eupblqdQ/

**Tasks**
- [ ] Quick Feasibility Check - New Email / New Parameters / New Triggers Only
- [ ] If the new email will be a functional replacement for an existing email, then in settings.py find the constant associated with that email, i.e. HUBSPOT_EMAIL_ID_FOO, and replace the default value with the new "test-" email id. This makes sure that QA will now be using the new email template for that email.

**Acceptance Tests**
- [ ] Validate that `custom.employee_first_name` is populated in the final email and it is the expected value
